# Generated by Django 5.2.7 on 2025-10-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_calculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao_texto', models.CharField(max_length=255)),
                ('intervalo_a', models.FloatField()),
                ('intervalo_b', models.FloatField()),
                ('metodo_utilizado', models.CharField(max_length=50)),
                ('resultado', models.FloatField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Calculo',
        ),
        migrations.DeleteModel(
            name='FerramentaLog',
        ),
    ]
