# Generated by Django 5.2.7 on 2025-10-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_analise_delete_calculo_delete_ferramentalog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analise',
        ),
    ]
