# Generated by Django 5.2.7 on 2025-11-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculadora', '0004_delete_analise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Sessão sem nome', max_length=100)),
                ('tipo_ferramenta', models.CharField(max_length=50)),
                ('metodo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('dados_input', models.JSONField()),
                ('dados_output', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
